theme: jekyll-theme-minimal
title: Utsav Awasthi
description: Ph.D. Candidate at University of Connecticut
logo: https://media.licdn.com/dms/image/D4E35AQEmJfsvfyZizQ/profile-framedphoto-shrink_200_200/0/1670469735046?e=1675198800&v=beta&t=R0hOhpPgbdbBSHeqgtKsakq4Se2rcWObe50GRlOK2cY
show_downloads: false
